dev_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('main.urls')),
    path('accounts/', include('registration.backends.simple.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

app_name = 'blog'

urlpatterns = [
	path('', views.index, name='index'),
	path('add_article/', views.add_article, name='add_article'),
	path('article/<slug:article_title_slug>/', views.show_article, name='show_article'),
	path('article/<slug:article_title_slug>/delete_article/', views.delete_article, name='delete_article'),
	path('article/<slug:article_title_slug>/edit_article/', views.edit_article, name='edit_article'),
	path('article/<slug:article_title_slug>/add_like/', views.add_like, name='add_like'),
	path('article/<slug:article_title_slug>/add_lislike/', views.add_dislike, name='add_dislike'),
	path('article/<slug:article_title_slug>/add_comment/', views.add_comment, name='add_comment'),
	path('article/<slug:article_title_slug>/delete_comment/<slug:comment_id>', views.delete_comment, name='delete_comment'),
	path('article/<slug:article_title_slug>/<slug:comment_id>/add_like', views.add_comment_like, name='add_comment_like'),
	path('article/<slug:article_title_slug>/<slug:comment_id>/add_comment_dislike', views.add_comment_dislike, name='add_comment_dislike'),

]

templates/blog/add_article.html
{% extends 'blog/base.html' %}

{% block title_block %}
    Add an Article
{% endblock %}

{% block body_block %}
    <h1>Add an Article</h1>
    <div>
        <form id="article_form" method="post" action="{% url 'blog:add_article' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Create Article" />
        </form>
    </div>
{% endblock %}

templates/blog/add_comment.html
{% extends 'blog/base.html' %}

{% block title_block %}
    Add Comment
{% endblock %}

{% block body_block %}
    <h1>Add Comment</h1>
    <div>
        <form id="comment_form" method="post" action="{% url 'blog:add_comment' article.slug %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Add Comment" />
        </form>
    </div>
{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
{% load static %}

<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
		{% block title_block %}
			DevBlog
		{% endblock %}
	</head>
	<body>
		<div>
			{% block body_block %}
			{% endblock %}
		</div>
		<div>
			<ul>
				<li><a href="{% url 'blog:index' %}">Main</a></li>
        {% if user.is_authenticated %}
					<li><a href="{% url 'blog:add_article' %}">Add Article</a></li>
					<li><a href="{% url 'auth_logout' %}?next={% url 'blog:index' %}">Logout</a></li>
					<li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
				{% else %}
					<li><a href="{% url 'auth_login' %}">Login</a></li>
					<li><a href="{% url 'registration_register' %}">Registration</a></li>
				{% endif %}
			</ul>
		</div>
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpujzy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
	</body>
</html>

templates/blog/edit_article.html
{% extends 'blog/base.html' %}

{% block title_block %}
	Edit Article
{% endblock %}

{% block body_block %}
    <h1>Edit Article</h1>
    <div>
        <form id="article_form" method="post" action="{% url 'blog:edit_article' article.slug %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" name="submit" value="Edit Article" />
        </form>
    </div>
{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title_block %}
	Main Page
{% endblock %}
{% block body_block %}
	{% if articles %}
		{% for article in articles %}
		    <div class="container">
				<div class="card text-center">
					<div class="card-header">
						<a href="{% url 'blog:show_article' article.slug %}">{{ article.title }}</a>
					</div>
		
					<div class="card-body">
						<img src="{{ MEDIA_URL }}{{ article.image }}" alt="Article image" />
					</div>
					
					<div class="card-footer text-muted">
						<p>{{ article.text }}</p>
					</div>
				</div>
			</div>
		    <hr />
		{% endfor %}
	{% else %}
		<div>
			No articles.
		</div>
	{% endif %}
{% endblock %}

templates/blog/show_article.html
{% extends 'blog/base.html' %}

{% block title_block %}
	{{ article.title }}
{% endblock %}

{% block body_block %}
	<div class="container">
		<div class="card text-center">
			<div class="card-header">
				{{ article.title }}
			</div>

			<div class="card-body">
				<img src="{{ MEDIA_URL }}{{ article.image }}" alt="Article image" />
			</div>

			<div class="card-footer text-muted">
				<p>{{ article.text }}</p>
				<p>{{ likes }}</p>
				{% if user.is_authenticated %}
					<a class="btn btn-secondary" href="{% url 'blog:add_like' article.slug %}" role="button">Like</a>
					<a class="btn btn-secondary" href="{% url 'blog:add_dislike' article.slug %}" role="button">Dislike</a>
	    		<a class="btn btn-secondary" href="{% url 'blog:add_comment' article.slug %}" role="button">Add Comment</a>
					{% if user == article.user %}
						<a class="btn btn-secondary" href="{% url 'blog:delete_article' article.slug %}" role="button">Delete Article</a>
						<a class="btn btn-secondary" href="{% url 'blog:edit_article' article.slug %}" role="button">Edit Article</a>
	    		{% endif %}
				{% endif %}
			</div>
				{% if comments %}
					{% for comment in comments %}
						<div class="card">
							<div class="card-body">
								{{ comment.text }}
								{{ comment.user }}
								{% if user == comment.user %}
									<a class="btn btn-secondary" href="{% url 'blog:delete_comment' article.slug comment.id %}" role="button">Delete Comment</a>
								{% endif %}
								{{ comment.comment_likes.all.count }}
								<a class="btn btn-secondary" href="{% url 'blog:add_comment_like' article.slug comment.id %}" role="button">Like</a>
								{{ comment.comment_dislikes.all.count }}
								<a class="btn btn-secondary" href="{% url 'blog:add_comment_dislike' article.slug comment.id %}" role="button">Dislike</a>
							</div>
						</div>
					{% endfor %}
				{% else %}
					No comments for this article
				{% endif %}
		</div>
	</div>
{% endblock %}